### ISSUE TITLE
Capacitor C22

### ISSUE THREAD

**Issue by bertrandmc** [cctvfm/quadtec101#1]
The yellow build guide indicates that the 100nF Ceramic capacitors should be placed in C22 but the PCB symbol indicates C22 is a Film capacitor.

**Comment by bertrandmc** [comment]
The yellow build guide indicates that the 100nF Ceramic capacitors should be placed in C22 but the PCB symbol indicates C22 is a Film capacitor.

**Comment by cctvfm** [comment]
Files have been updated, There's a few kits still floating around with the square footprint. Always go by the BOM, not the shapes on the PCB!
